FROM node:20-alpine

WORKDIR /app

COPY packages/common ./packages/common
COPY package.json ./
COPY packages/SERVICE_NAME_PLACEHOLDER ./packages/SERVICE_NAME_PLACEHOLDER

RUN npm install --workspace=packages/SERVICE_NAME_PLACEHOLDER --omit=dev

ENV NODE_ENV=production

CMD ["node", "packages/SERVICE_NAME_PLACEHOLDER/src/index.js"]
