FROM node:20.11.1-alpine3.19

WORKDIR /app

COPY packages/common ./packages/common
COPY package.json ./
COPY package-lock.json ./
COPY packages/chat-service ./packages/chat-service

RUN apk add --no-cache curl
RUN npm install --workspace=packages/chat-service --omit=dev

ENV NODE_ENV=production

CMD ["node", "packages/chat-service/src/index.js"]
