FROM node:22-alpine

WORKDIR /app

COPY packages/common ./packages/common
COPY package.json ./
COPY package-lock.json ./
COPY packages/product-service ./packages/product-service

RUN apk add --no-cache curl
RUN npm install --workspace=packages/product-service --omit=dev

ENV NODE_ENV=production

CMD ["node", "packages/product-service/src/index.js"]
