FROM node:22-alpine

WORKDIR /app

COPY packages/common ./packages/common
COPY package.json ./
COPY packages/order-service ./packages/order-service

RUN apk add --no-cache curl
RUN npm install --workspace=packages/order-service --omit=dev

ENV NODE_ENV=production

CMD ["node", "packages/order-service/src/index.js"]
