FROM node:20-alpine

WORKDIR /app

COPY packages/common ./packages/common
COPY package.json ./
COPY packages/user-service ./packages/user-service

RUN npm install --workspace=packages/user-service --omit=dev

ENV NODE_ENV=production

CMD ["node", "packages/user-service/src/index.js"]
