FROM node:22-alpine

WORKDIR /app

COPY packages/common ./packages/common
COPY package.json ./
COPY package-lock.json ./
COPY packages/notification-service ./packages/notification-service

RUN apk add --no-cache curl
RUN npm install --workspace=packages/notification-service --omit=dev

ENV NODE_ENV=production

CMD ["node", "packages/notification-service/src/index.js"]
