FROM node:20-alpine

WORKDIR /app

COPY packages/common ./packages/common
COPY package.json ./
COPY packages/lost-found-service ./packages/lost-found-service

RUN apk add --no-cache curl
RUN npm install --workspace=packages/lost-found-service --omit=dev

ENV NODE_ENV=production

CMD ["node", "packages/lost-found-service/src/index.js"]
