FROM node:22-alpine
WORKDIR /app
COPY package.json packages/ws-gateway/package.json packages/common/package.json ./
COPY packages/common/ ./packages/common/
COPY packages/ws-gateway/ ./packages/ws-gateway/
RUN npm install --omit=dev
COPY packages/ws-gateway/src ./src
CMD ["node", "src/index.js"]
