server:
  port: 8086
spring:
  application:
    name: lost-found-service
  config:
    import: "optional:configserver:http://config-admin:config-admin-password@localhost:8888"
  data:
    mongodb:
      uri: mongodb://root:iuh_exchange_root@localhost:27018/?authMechanism=SCRAM-SHA-1&authSource=admin
      database: iuh_lostfound
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-admin:eureka-admin-password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# AWS S3 Config (đọc từ Window Environment / file .env)
aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME:s3-vinhtran}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    presigned-url-expiry: 300  # 5 phút

management:
  endpoints:
    web:
      exposure:
        include: health,info
