apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iuh-exchange
  namespace: iuh-exchange
spec:
  rules:
    - host: iuh-exchange.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: ws-gateway
                port:
                  number: 3007
